"""adiciona_redacao_e_correcao

Revision ID: 68348fb2d833
Revises: 1a2b3c4d5e6f
Create Date: 2026-08-07 15:17:25.813995

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "68348fb2d833"
down_revision: str | Sequence[str] | None = "1a2b3c4d5e6f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "redacoes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("matricula_id", sa.Integer(), nullable=False),
        sa.Column("aula_id", sa.Integer(), nullable=False),
        sa.Column("texto", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("data_entrega", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["aula_id"], ["aulas.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["matricula_id"], ["matriculas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("matricula_id", "aula_id", name="uq_redacao_matricula_aula"),
    )
    op.create_index(op.f("ix_redacoes_aula_id"), "redacoes", ["aula_id"], unique=False)
    op.create_index(op.f("ix_redacoes_matricula_id"), "redacoes", ["matricula_id"], unique=False)
    op.create_table(
        "correcoes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("redacao_id", sa.Integer(), nullable=False),
        sa.Column("nota_c1", sa.Integer(), nullable=False),
        sa.Column("nota_c2", sa.Integer(), nullable=False),
        sa.Column("nota_c3", sa.Integer(), nullable=False),
        sa.Column("nota_c4", sa.Integer(), nullable=False),
        sa.Column("nota_c5", sa.Integer(), nullable=False),
        sa.Column("comentario_geral", sa.Text(), nullable=True),
        sa.Column("data_correcao", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["redacao_id"], ["redacoes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("redacao_id"),
    )
    op.add_column("aulas", sa.Column("tema", sa.String(length=200), nullable=True))
    op.add_column("aulas", sa.Column("texto_apoio", sa.Text(), nullable=True))
    op.add_column("aulas", sa.Column("comando", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("aulas", "comando")
    op.drop_column("aulas", "texto_apoio")
    op.drop_column("aulas", "tema")
    op.drop_table("correcoes")
    op.drop_index(op.f("ix_redacoes_matricula_id"), table_name="redacoes")
    op.drop_index(op.f("ix_redacoes_aula_id"), table_name="redacoes")
    op.drop_table("redacoes")
    # ### end Alembic commands ###
