"""adiciona_upload_proposta_e_redacao

Revision ID: bf4fe48c4206
Revises: 68348fb2d833
Create Date: 2026-08-07 16:34:30.264430

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bf4fe48c4206"
down_revision: str | Sequence[str] | None = "68348fb2d833"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("aulas", sa.Column("proposta_arquivo", sa.String(length=255), nullable=True))
    op.add_column("redacoes", sa.Column("arquivo_path", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("redacoes", "arquivo_path")
    op.drop_column("aulas", "proposta_arquivo")
    # ### end Alembic commands ###
